<a href="https://colab.research.google.com/github/reyfdz/Proyecto-final/blob/main/bernoulli_Entregable1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from scipy.stats import bernoulli
import numpy as np
import sympy
from sympy.abc import x, z, n

In [ ]:
fp = bernoulli(0.7)
fp.rvs(30)

array([0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 1])

In [ ]:
sum(fp.rvs(30))/30 #la proporcion es la suma de todos los 1 entre el total

0.7

In [ ]:
xs = fp.rvs(100)
sum(xs)/100 # entre ms grande sea el numero mejor es la aproximidad a la probabilidad real

0.64

In [ ]:
xs

array([1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

In [ ]:
p = sympy.symbols("p", positive = True)

In [ ]:
np.cumsum(xs)

array([ 1,  2,  2,  3,  3,  3,  3,  4,  4,  5,  6,  7,  8,  9, 10, 11, 11,
       12, 13, 13, 14, 14, 15, 16, 17, 18, 18, 19, 19, 20, 20, 20, 21, 21,
       22, 23, 24, 25, 26, 27, 28, 28, 29, 29, 30, 30, 31, 32, 33, 34, 35,
       36, 36, 37, 38, 39, 39, 39, 39, 40, 41, 42, 43, 44, 45, 45, 45, 46,
       46, 47, 48, 48, 49, 50, 50, 51, 52, 52, 53, 54, 55, 55, 56, 56, 57,
       58, 58, 59, 59, 59, 59, 60, 60, 61, 61, 62, 62, 63, 63, 64])

In [ ]:
f = p**x*(1-p)**(1-x)
f

p**x*(1 - p)**(1 - x)

In [ ]:
#p con gorrito es el maximo verosimil, el que mas se aproxima a la variable

In [ ]:
J = np.prod([f.subs(x, i)for i in xs])
logJ = sympy.expand_log(sympy.log(J))
print(J)
print(logJ)

p**64*(1 - p)**36
64*log(p) + log((1 - p)**36)


In [ ]:
phat = sympy.solve(sympy.diff(logJ,p),p)[0]
phat

16/25

Ejercicios:

Investigación:

a. Menciona 5 aplicaciones de la variable aleatoria exponencial.

b. ¿Qué aplicaciones de la exponencial podrían ser de utilidad en tu carrera?

Crea una muestra aleatoria de 1000 datos tomados a partir de una muestra aleatoria exponencial.

Calcula el MLE para tu conjunto de datos.

In [ ]:

from sympy import exp
l = sympy.symbols("l", positive = True)
f = (1/l**1000)*exp(-13/l)
logf = sympy.expand_log(sympy.log(f))
lhat = sympy.solve(sympy.diff(logf,l),l)[0]

print("El estimador MLE es", lhat)

El estimador MLE es 13/1000
